# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ca55843d7925c85aee863e4b09394fceccf89a2b1e492b472ee810f3c2165f016b795e47fe35ca867aae15a6284a804447a906e0f5f0af9c6e575d4a3fad5e6

test:
  secret_key_base: 8592946982e5ee2acaecf7ba246654e0edfb7fdf8abae8c9a60af02c6d12fc88c37541fc2cc5f6687d085a38f1a005554a918219e10666f9c51c6056e5512537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
